/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.Point;
import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.*;

/**
 *
 * @author Billy
 */
public class TextEditor extends javax.swing.JFrame {
    
    private Viterbi v;
    private TextParser parser;
    private Dictionary d;
    private Thesaurus th;

    /**
     * Creates new form TextEditor
     */
    public TextEditor() {
        initComponents();
    }
    
    public void InitializeStuff() {
        try {
            // initialize 
            try {
                v = new Viterbi("corpus_tagset.txt", "corpus_simple_tagset.txt", "datafile.txt");
                parser = new TextParser(v);
            }
            catch (    FileNotFoundException | WrongFormatException | POSNotFoundException ex) {
                v = new Viterbi("backup/corpus_tagset.txt", "backup/corpus_simple_tagset.txt", "backup/datafile.txt");
                parser = new TextParser(v);
            }
            
            try {
                d = new Dictionary("webster_dictionary.txt");
            }
            catch (FileNotFoundException ex) {
                d = new Dictionary("backup/webster_dictionary.txt");
            }
            
            try {
                th = new Thesaurus("thesaurus.txt");
            }
            catch (FileNotFoundException ex) {
                th = new Thesaurus("backup/thesaurus.txt");
            }

            Style style = legendText.addStyle(getColor(0), null);
            StyleConstants.setForeground(style, Color.decode(getColor(0)));
            for (int i=1; i<15; i++)
            {
                style = legendText.addStyle(getColor(i), null);
                StyleConstants.setForeground(style, Color.decode(getColor(i)));
            }
            StyledDocument doc = legendText.getStyledDocument();
            for (int i=0; i<POS.numgIndices(); i++) {
                try {
                    if (i == POS.numgIndices()-1) doc.insertString(doc.getLength(), POS.getgNameBygIndex(i), legendText.getStyle(getColor(i)));
                    else doc.insertString(doc.getLength(), POS.getgNameBygIndex(i)+"\n", legendText.getStyle(getColor(i)));
                } catch (BadLocationException ex) {
                    Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } catch (    FileNotFoundException | WrongFormatException | POSNotFoundException ex) {
            Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textEditorPane = new javax.swing.JTextPane();
        tagButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taggedTextPane = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        legendText = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dictionaryText = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        thesaurusText = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuOptions = new javax.swing.JMenu();
        menuCorpus = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Part of Speech Tagger");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Text Editor"));
        jPanel1.setName("");

        textEditorPane.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(textEditorPane);

        tagButton.setText("Tag");
        tagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 418, Short.MAX_VALUE)
                        .addComponent(tagButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagButton)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tagged Text"));

        taggedTextPane.setEditable(false);
        taggedTextPane.setName("");
        taggedTextPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taggedTextPaneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taggedTextPane);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Legend"));

        legendText.setEditable(false);
        jScrollPane6.setViewportView(legendText);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dictionary"));

        dictionaryText.setColumns(20);
        dictionaryText.setEditable(false);
        dictionaryText.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        dictionaryText.setLineWrap(true);
        dictionaryText.setRows(5);
        dictionaryText.setBorder(null);
        jScrollPane3.setViewportView(dictionaryText);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thesaurus"));

        jScrollPane5.setViewportView(thesaurusText);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        menuFile.setText("File");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        menuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        menuFile.add(menuNew);

        menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOpen.setText("Open");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuOpen);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuSave.setText("Save");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuSave);

        jMenuBar1.add(menuFile);

        menuOptions.setText("Options");

        menuCorpus.setText("Corpus");
        menuCorpus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCorpusActionPerformed(evt);
            }
        });
        menuOptions.add(menuCorpus);

        jMenuBar1.add(menuOptions);

        jMenu1.setText("Help");

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbout);

        menuHelp.setText("Help");
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });
        jMenu1.add(menuHelp);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static String getColor(int n) {
        String[] colors = new String[15];
        colors[0] = "#ED1F24";
        colors[1] = "#371BC9";
        colors[2] = "#C0BA0E";
        colors[3] = "#2C9540";
        colors[4] = "#8215BB";
        colors[5] = "#D88019";
        colors[6] = "#39B493";
        colors[7] = "#59B919";
        colors[8] = "#d978CA";
        colors[9] = "#959595";
        colors[10] = "#000000";
        colors[11] = "#875820";
        colors[12] = "#900018";
        colors[13] = "#047EB1";
        colors[14] = "#A77FAA";
        return colors[n%15];
    }
    
    private void ChooseNewCorpus() {
        JFileChooser chooser = new JFileChooser();

        chooser.setDialogTitle("Choose corpus");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showOpenDialog(null);

        if(returnVal == JFileChooser.APPROVE_OPTION) {
            String corpusPath = chooser.getSelectedFile().getPath();
            chooser.setDialogTitle("Choose tagset");
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            returnVal = chooser.showOpenDialog(null);

            if(returnVal == JFileChooser.APPROVE_OPTION) {
                String tagsetPath = chooser.getSelectedFile().getPath();
                chooser.setDialogTitle("Choose simple tagset");
                chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
                returnVal = chooser.showOpenDialog(null);

                if(returnVal == JFileChooser.APPROVE_OPTION) {
                    try {
                        String simpleTagsetPath = chooser.getSelectedFile().getPath();

                        File source = new File(tagsetPath);
                        File destination = new File("corpus_tagset.txt");
                        source.renameTo(destination);

                        source = new File(simpleTagsetPath);
                        destination = new File("corpus_simple_tagset.txt");
                        source.renameTo(destination);

                        Viterbi.loadCorpusForTraining("corpus_tagset.txt", "corpus_simple_tagset.txt", corpusPath, "datafile.txt");
                        v = new Viterbi("corpus_tagset.txt", "corpus_simple_tagset.txt", "datafile.txt");
                        parser = new TextParser(v);
                    } catch (                IOException | WrongFormatException | POSNotFoundException ex) {
                        try {
                            v = new Viterbi("backup/corpus_tagset.txt", "backup/corpus_simple_tagset.txt", "backup/datafile.txt");
                            parser = new TextParser(v);
                            JOptionPane.showMessageDialog(null, "Invalid files. Please choose again.", "Error", JOptionPane.PLAIN_MESSAGE);
                        }
                        catch (                IOException | WrongFormatException | POSNotFoundException ex2) {
                            Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex2);
                        }
                    }
                }
            }
        }
    }
    
    private void taggedTextPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taggedTextPaneMouseClicked
        try {
            Point pt = new Point(evt.getX(), evt.getY());
            int pos = taggedTextPane.viewToModel(pt);
            int start = Utilities.getWordStart(taggedTextPane, pos);
            int end = Utilities.getWordEnd(taggedTextPane, pos);
            String dictWord = taggedTextPane.getText(start, end-start);
            thesaurusText.setText(th.lookup(dictWord));
            dictionaryText.setText(dictWord.toUpperCase() + "\n\n" + d.lookup(dictWord));
            thesaurusText.setCaretPosition(0);
            dictionaryText.setCaretPosition(0);
            StyledDocument doc = taggedTextPane.getStyledDocument();
            Style style = taggedTextPane.addStyle("bgh", null);
            StyleConstants.setBackground(style, Color.decode("#E0E0E0"));
            style = taggedTextPane.addStyle("bg", null);
            StyleConstants.setBackground(style, Color.decode("#FFFFFF"));
            doc.setCharacterAttributes(0, doc.getLength(), taggedTextPane.getStyle("bg"), false);
            doc.setCharacterAttributes(start, end-start, taggedTextPane.getStyle("bgh"), false);
        } catch (BadLocationException ex) {
            Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_taggedTextPaneMouseClicked

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFileActionPerformed

    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
        textEditorPane.setText("");
        taggedTextPane.setText("");
        dictionaryText.setText("");
        thesaurusText.setText("");
    }//GEN-LAST:event_menuNewActionPerformed

    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            BufferedReader br = null;
            try {
                br = new BufferedReader(new FileReader(chooser.getSelectedFile().getPath()));
                try {
                    StringBuilder sb = new StringBuilder();
                    String line = null;
                    try {
                        line = br.readLine();
                    } catch (IOException ex) {
                        Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    while (line != null) {
                        sb.append(line);
                        sb.append("\n");
                        try {
                            line = br.readLine();
                        } catch (IOException ex) {
                            Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    String everything = sb.toString();
                    textEditorPane.setText(everything);
                } finally {
                    try {
                        br.close();
                    } catch (IOException ex) {
                        Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    br.close();
                } catch (IOException ex) {
                    Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_menuOpenActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showSaveDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            FileWriter outFile = null;
            try {
                outFile = new FileWriter(chooser.getSelectedFile());
                try (PrintWriter out = new PrintWriter(outFile)) {
                    out.print(textEditorPane.getText());
                }
            } catch (IOException ex) {
                Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    outFile.close();
                } catch (IOException ex) {
                    Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        JOptionPane.showMessageDialog(null, "Part of Speech Tagger created by Billy Janitsch, Jenny Liu, Yuechen Zhao, and Joy Zheng.", "About", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        JOptionPane.showMessageDialog(null, "Type English-language text into the text editor pane, and then click 'Tag' to have its parts of speech identified.\n"
                + "Click on individual words to view their definitions and thesaurus entries.", "Help", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_menuHelpActionPerformed

    private void tagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagButtonActionPerformed
        try {
            Style style = taggedTextPane.addStyle(getColor(0), null);
            StyleConstants.setForeground(style, Color.decode(getColor(0)));
            for (int i=1; i<15; i++)
            {
                style = taggedTextPane.addStyle(getColor(i), null);
                StyleConstants.setForeground(style, Color.decode(getColor(i)));
            }
            
            taggedTextPane.setText("");
            ArrayList<ArrayList<Pair<String, POS>>> sentenceList = parser.parse(textEditorPane.getText());
            for (int i=0; i<sentenceList.size(); i++) {
                for (int j=0; j<sentenceList.get(i).size(); j++) {
                    StyledDocument doc = taggedTextPane.getStyledDocument();
                    try {
                        doc.insertString(doc.getLength(), sentenceList.get(i).get(j).get_first(),
                                taggedTextPane.getStyle(getColor(sentenceList.get(i).get(j).get_second().getgIndex())));
                    } catch (BadLocationException ex) {
                        Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            
            dictionaryText.setText("");
            thesaurusText.setText("");
        } catch (POSNotFoundException ex) {
            Logger.getLogger(TextEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tagButtonActionPerformed

    private void menuCorpusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCorpusActionPerformed
        ChooseNewCorpus();
    }//GEN-LAST:event_menuCorpusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TextEditor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dictionaryText;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane legendText;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuCorpus;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuHelp;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenu menuOptions;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JButton tagButton;
    private javax.swing.JTextPane taggedTextPane;
    private javax.swing.JTextPane textEditorPane;
    private javax.swing.JTextPane thesaurusText;
    // End of variables declaration//GEN-END:variables
}
